### PR TITLE
[WIP] JDC edits

### PR DESCRIPTION
**Pull request by jchodera**
So far, this is just some edits to the introduction. I'll continue with edits to the statistical analysis section.

### CODE REVIEW

**Comment by ppxasjsm** [comment]
@jchodera how is the WIP coming along here?

**Comment by jchodera** [comment]
Working on it again today!

**Comment by ppxasjsm** [comment]
@jchodera, I will close this, as I would like to move things along.

**Comment by ppxasjsm** [comment]
I incorporated your changes into the manuscript, but the pull request is now too old.

**Pull request closed without merging**
